sudo: required
services:
  - docker

before_install:
  - docker build -t cromulentscientist/docker-react -f Dockerfile.dev .

script:
  - docker run cromulentscientist/docker-react npm run test -- --coverage
