sudo: required
services:
  - docker

before_install:
  - docker build -t cromulentscientist/docker-react -f Dockerfile.dev .
script:
  - docker run cromulentscientist/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "travis-docker-eb"
  env: "TravisDockerEb-env"
  bucket_name: "elasticbeanstalk-us-west-2-004190587247"
  bucket_path: "travis-docker-eb"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
